// <auto-generated />
using System;
using KoiShowManagementSystem.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoiShowManagementSystem.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241114082227_InitDBv1")]
    partial class InitDBv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                // Thiết lập thông tin phiên bản sản phẩm và giới hạn độ dài định danh
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Sử dụng Identity Columns cho SQL Server (tự động tăng giá trị)
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Định nghĩa bảng Event_Koi_Participations
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.Event_Koi_Participation", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng giá trị
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Sử dụng Identity Column cho trường Id
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category") // Thể loại cá Koi tham gia sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventsId") // Khóa ngoại tham chiếu đến bảng Events
                        .HasColumnType("int");

                    b.Property<int>("KoiId") // Khóa ngoại tham chiếu đến bảng Koi
                        .HasColumnType("int");

                    b.Property<float>("Score") // Điểm của cá Koi
                        .HasColumnType("real");

                    b.HasKey("Id"); // Thiết lập khóa chính cho bảng

                    b.HasIndex("EventsId"); // Tạo chỉ mục (index) cho cột EventsId

                    b.HasIndex("KoiId"); // Tạo chỉ mục (index) cho cột KoiId

                    b.ToTable("Event_Koi_Participations"); // Tên bảng trong cơ sở dữ liệu
                });

            // Định nghĩa bảng Events
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.Events", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng giá trị
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description") // Mô tả sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate") // Ngày kết thúc sự kiện
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName") // Tên sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location") // Địa điểm tổ chức sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate") // Ngày bắt đầu sự kiện
                        .HasColumnType("datetime2");

                    b.Property<string>("Status") // Trạng thái của sự kiện (vd: "active", "completed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id"); // Thiết lập khóa chính cho bảng

                    b.ToTable("Events"); // Tên bảng trong cơ sở dữ liệu
                });

            // Định nghĩa bảng JudgeAssignments (Phân công giám khảo)
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.JudgeAssignments", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng giá trị
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnventsId") // Lỗi chính tả, đáng ra là "EventsId"
                        .HasColumnType("int");

                    b.Property<int>("EventsId") // Khóa ngoại tham chiếu đến bảng Events
                        .HasColumnType("int");

                    b.Property<int>("UsersId") // Khóa ngoại tham chiếu đến bảng Users
                        .HasColumnType("int");

                    b.HasKey("Id"); // Thiết lập khóa chính

                    b.HasIndex("EventsId"); // Tạo chỉ mục (index) cho cột EventsId

                    b.HasIndex("UsersId"); // Tạo chỉ mục (index) cho cột UsersId

                    b.ToTable("JudgeAssignments"); // Tên bảng trong cơ sở dữ liệu
                });

            // Tiếp tục định nghĩa các bảng khác (Koi, Reports, Scores, Users)...
            // Lưu ý: Cấu trúc bảng được định nghĩa bằng cách chỉ rõ các trường, khóa chính, khóa ngoại và quan hệ giữa các bảng.
#pragma warning restore 612, 618
        }
    }
}
