// <auto-generated />
using System;
using KoiShowManagementSystem.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoiShowManagementSystem.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241114082227_InitDBv1")]
    partial class InitDBv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                // Thiết lập phiên bản sản phẩm và độ dài tối đa của định danh.
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Sử dụng Identity Columns cho SQL Server
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Định nghĩa bảng Event_Koi_Participations
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.Event_Koi_Participation", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category") // Thể loại của sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventsId") // Khóa ngoại tham chiếu đến bảng Events
                        .HasColumnType("int");

                    b.Property<int>("KoiId") // Khóa ngoại tham chiếu đến bảng Koi
                        .HasColumnType("int");

                    b.Property<float>("Score") // Điểm của cá Koi trong sự kiện
                        .HasColumnType("real");

                    b.HasKey("Id"); // Thiết lập khóa chính

                    b.HasIndex("EventsId"); // Tạo chỉ mục cho EventsId

                    b.HasIndex("KoiId"); // Tạo chỉ mục cho KoiId

                    b.ToTable("Event_Koi_Participations"); // Tên bảng trong CSDL
                });

            // Định nghĩa bảng Events
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.Events", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description") // Mô tả sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate") // Ngày kết thúc sự kiện
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName") // Tên sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location") // Địa điểm tổ chức
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate") // Ngày bắt đầu sự kiện
                        .HasColumnType("datetime2");

                    b.Property<string>("Status") // Trạng thái của sự kiện
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            // Định nghĩa bảng JudgeAssignments (Phân công giám khảo)
            modelBuilder.Entity("KoiShowManagementSystem.Repositories.Entity.JudgeAssignments", b =>
                {
                    b.Property<int>("Id") // Khóa chính, tự tăng
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnventsId") // Khóa ngoại bị lỗi chính tả, đáng ra là "EventsId"
                        .HasColumnType("int");

                    b.Property<int>("EventsId") // Khóa ngoại tham chiếu đến bảng Events
                        .HasColumnType("int");

                    b.Property<int>("UsersId") // Khóa ngoại tham chiếu đến bảng Users
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventsId");

                    b.HasIndex("UsersId");

                    b.ToTable("JudgeAssignments");
                });

            // Tiếp tục thêm các bảng khác (Koi, Reports, Scores, Users) tương tự...
            // Lưu ý: Cấu trúc bảng luôn được định nghĩa bằng cách chỉ rõ các trường, khóa ngoại và bảng tham chiếu.
        }
    }
}
